version: '3'
services:
  backend:
    build: ./backend
    image: ritsuna/backend:latest
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    image: ritsuna/frontend:latest
    ports:
      - "3000:3000"
